# Generated by Django 3.2 on 2021-05-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=12555, verbose_name='Описание')),
                ('hours', models.PositiveIntegerField(blank=True, verbose_name='Количество часов')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Цена')),
                ('count_themes', models.PositiveIntegerField(blank=True, verbose_name='Количество тем')),
            ],
            options={
                'verbose_name': ('Курс',),
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название задания')),
                ('task', models.FileField(blank=True, upload_to='', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=12555, verbose_name='Описание задания')),
            ],
            options={
                'verbose_name': ('Задание',),
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
