# Generated by Django 3.2 on 2021-05-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_1',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='task',
            name='file_2',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='Файл'),
        ),
    ]
